angular = require('angular')

angular.module('ad3', [])

require('./services/d3service')
require('./services/d3locale')
require('./directives/arc')
require('./directives/area')
require('./directives/axis')
require('./directives/bars')
require('./directives/chart')
require('./directives/data')
require('./directives/gradient')
require('./directives/include')
require('./directives/line')
require('./directives/pie')
